# Generated by Django 6.1 on 2026-09-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('destination', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=5000)),
                ('status', models.CharField(choices=[('PLANNED', 'Geplant'), ('ACTIVE', 'Unterwegs'), ('DONE', 'Abgeschlossen'), ('CANCELLED', 'Storniert')], default='PLANNED', max_length=9)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('is_packed', models.BooleanField(default=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reisen.trip')),
            ],
            options={
                'ordering': ['is_packed', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=240)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reisen.trip')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reisen.trip')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Offen'), ('DONE', 'Erledigt')], default='OPEN', max_length=4)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reisen.trip')),
            ],
            options={
                'ordering': ['status', 'due_date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['owner', 'start_date'], name='reisen_trip_owner_i_6cf76a_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='trip_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('budget_amount__isnull', True), ('budget_amount__gte', 0), _connector='OR'), name='trip_budget_not_negative'),
        ),
        migrations.AddIndex(
            model_name='packingitem',
            index=models.Index(fields=['trip', 'is_packed'], name='reisen_pack_trip_id_40e3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='tripevent',
            index=models.Index(fields=['trip', 'starts_at'], name='reisen_trip_trip_id_668080_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripevent',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='trip_event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='tripexpense',
            index=models.Index(fields=['trip', 'date'], name='reisen_trip_trip_id_25755e_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripexpense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='trip_expense_not_negative'),
        ),
        migrations.AddIndex(
            model_name='triptask',
            index=models.Index(fields=['trip', 'status'], name='reisen_trip_trip_id_5554cd_idx'),
        ),
    ]
