# Generated by Django 6.1 on 2026-09-30 17:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='trip_end_after_start',
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 9, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 9, 30)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='trip_end_after_start'),
        ),
    ]
