# Generated by Django 6.1 on 2026-09-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0002_remove_trip_trip_end_after_start_alter_trip_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='baggage_type',
            field=models.CharField(blank=True, choices=[('HAND_LUGGAGE', 'Nur Handgepäck'), ('CHECKED_BAGGAGE', 'Aufgabegepäck'), ('CAR_LUGGAGE', 'Gepäck im Auto'), ('UNKNOWN', 'Noch unklar')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='trip',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('FLIGHT', 'Flugzeug'), ('TRAIN', 'Zug'), ('CAR', 'Auto'), ('BUS', 'Bus'), ('OTHER', 'Sonstiges')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('CITY_TRIP', 'Städtereise'), ('BEACH', 'Strandurlaub'), ('BUSINESS', 'Geschäftsreise'), ('ROAD_TRIP', 'Roadtrip'), ('ACTIVE', 'Aktivurlaub'), ('FAMILY', 'Familienreise'), ('GENERAL', 'Allgemein')], default='', max_length=10),
        ),
    ]
