# Generated by Django 6.1 on 2026-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0003_trip_baggage_type_trip_transport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingitem',
            name='category',
            field=models.CharField(choices=[('DOKUMENTE', 'Dokumente'), ('KLEIDUNG', 'Kleidung'), ('TECHNIK', 'Technik'), ('GESUNDHEIT', 'Gesundheit'), ('HYGIENE', 'Hygiene'), ('SONSTIGES', 'Sonstiges')], default='SONSTIGES', max_length=10),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='note',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
