# Generated by Django 6.1 on 2026-09-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0004_packingitem_category_packingitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptask',
            name='note',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
