# Generated by Django 6.1 on 2026-09-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0005_triptask_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US-Dollar'), ('GBP', 'Britisches Pfund'), ('CHF', 'Schweizer Franken')], default='EUR', max_length=3),
        ),
        migrations.CreateModel(
            name='TripBudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('TRANSPORT', 'Transport'), ('UNTERKUNFT', 'Unterkunft'), ('ESSEN', 'Essen'), ('AKTIVITAETEN', 'Aktivitäten'), ('SHOPPING', 'Shopping'), ('SONSTIGES', 'Sonstiges'), ('RESERVE', 'Reserve')], max_length=12)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='reisen.trip')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'category'), name='trip_budget_category_unique_per_trip'), models.CheckConstraint(condition=models.Q(('planned_amount__gte', 0)), name='trip_budget_category_not_negative')],
            },
        ),
    ]
