# Generated by Django 6.1 on 2026-10-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owner_as_participant(apps, schema_editor):
    """Jede schon bestehende Reise bekommt ihren Ersteller als Teilnehmer mit Rolle OWNER — sonst würde eine
    Solo-Reise aus der Zeit vor diesem Feature plötzlich ganz ohne Teilnehmer dastehen."""
    Trip = apps.get_model('reisen', 'Trip')
    TripParticipant = apps.get_model('reisen', 'TripParticipant')
    for trip in Trip.objects.all():
        TripParticipant.objects.get_or_create(trip=trip, user_id=trip.owner_id, defaults={'role': 'OWNER'})


class Migration(migrations.Migration):

    dependencies = [
        ('reisen', '0006_trip_currency_tripbudgetcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Besitzer'), ('EDITOR', 'Bearbeiter'), ('VIEWER', 'Betrachter')], default='VIEWER', max_length=6)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reisen.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_participant')],
            },
        ),
        migrations.RunPython(backfill_owner_as_participant, migrations.RunPython.noop),
    ]
