# Generated by Django 6.1 on 2026-09-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#5b3fd6', help_text='Hex-Farbwert, z. B. #5b3fd6.', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_key',
            field=models.CharField(default='sonstiges', max_length=30),
        ),
    ]
