# Generated by Django 6.1 on 2026-09-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0007_recurringdeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
