# Generated by Django 6.1 on 2026-09-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0011_transaction_datum_required_drop_occurred_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#164c49', help_text='Hex-Farbwert, z. B. #164c49.', max_length=7),
        ),
    ]
