# Generated by Django 6.1 on 2026-09-25 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_contributions(apps, schema_editor):
    """Bereits gesparte Beträge zählen ab dem Tag, an dem das Ziel angelegt wurde —
    sonst bliebe das schon eingegebene Gesparte ohne Wirkung auf das Budget."""
    SavingsGoal = apps.get_model('finanzen', 'SavingsGoal')
    SavingsContribution = apps.get_model('finanzen', 'SavingsContribution')
    for goal in SavingsGoal.objects.filter(current_amount__gt=0):
        if not SavingsContribution.objects.filter(goal=goal).exists():
            SavingsContribution.objects.create(
                owner_id=goal.owner_id, goal=goal, amount=goal.current_amount, date=goal.created_at.date()
            )


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0013_monthlybudget_savingsgoal_category_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finanzen.savingsgoal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['owner', 'date'], name='finanzen_sa_owner_i_74f4e0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='savings_contribution_not_zero')],
            },
        ),
        migrations.RunPython(backfill_contributions, migrations.RunPython.noop),
    ]
