# Generated by Django 6.1 on 2026-09-25 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0014_savings_contribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='end_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='open_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('end_month__isnull', True), ('end_month__gte', models.F('month')), _connector='OR'), name='monthly_budget_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='monthlybudget',
            constraint=models.CheckConstraint(condition=models.Q(('open_ended', False), ('end_month__isnull', True), _connector='OR'), name='monthly_budget_open_or_end'),
        ),
    ]
