# Generated by Django 6.1 on 2026-09-25 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0015_budget_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='plan_end_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='plan_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='plan_open_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_amount__isnull', True), ('monthly_amount__gt', 0), _connector='OR'), name='savings_goal_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_amount__isnull', True), ('plan_month__isnull', False), _connector='OR'), name='savings_goal_rate_has_start'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('plan_end_month__isnull', True), ('plan_end_month__gte', models.F('plan_month')), _connector='OR'), name='savings_goal_plan_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='savingsgoal',
            constraint=models.CheckConstraint(condition=models.Q(('plan_open_ended', False), ('plan_end_month__isnull', True), _connector='OR'), name='savings_goal_plan_open_or_end'),
        ),
    ]
