# Generated by Django 6.1 on 2026-09-25 15:08

from django.db import migrations


def backfill_goal_period(apps, schema_editor):
    """Bisherige Ziele galten für alle Monate. Ab jetzt gilt ein Ziel nur in seinem Zeitraum; damit nichts
    in fremden Monaten auftaucht, gilt jedes bestehende Ziel für den Monat, in dem es angelegt wurde.
    Ziele mit Sparrate haben ihren Zeitraum schon und bleiben unverändert."""
    SavingsGoal = apps.get_model('finanzen', 'SavingsGoal')
    for goal in SavingsGoal.objects.filter(plan_month__isnull=True):
        goal.plan_month = goal.created_at.date().replace(day=1)
        goal.save(update_fields=['plan_month'])


class Migration(migrations.Migration):

    dependencies = [
        ('finanzen', '0017_private_category_colors'),
    ]

    operations = [
        migrations.RunPython(backfill_goal_period, migrations.RunPython.noop),
    ]
