"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1, seitdem gehärtet
gemäß ARCHITEKTUR.md Abschnitt 3 (Cybersecurity-Konzept).

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
# .env liegt in backend/ (siehe .env.example im Repo-Root für die
# Docker-Variante).
environ.Env.read_env(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# Bewusst: DEBUG ist standardmäßig False und muss aktiv per .env auf True
# gesetzt werden – so kann DEBUG nie versehentlich in Produktion aktiv sein.
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # von django-allauth benötigt (Site-Framework für Multi-Site-Setups)
    'django.contrib.sites',
    'rest_framework',
    'rest_framework_simplejwt',
    # ermöglicht Refresh-Token-Rotation mit serverseitiger Invalidierung
    # (ARCHITEKTUR.md §3.1), siehe SIMPLE_JWT weiter unten
    'rest_framework_simplejwt.token_blacklist',
    'allauth',
    'allauth.account',
    'corsheaders',
    'csp',
    'axes',
    # Fachliche Module, siehe ARCHITEKTUR.md §2.1
    'core',
    'finanzen',
    'haushalt',
    'organisation',
    'integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # muss laut django-axes-Doku die letzte Middleware in der Liste sein
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # muss vor ModelBackend stehen, damit Axes Login-Versuche zählen kann
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# ARCHITEKTUR.md §2.2: SQLite serialisiert Schreibzugriffe über einen
# einzigen Lock und ist daher KEINE Produktionsdatenbank für Mehrbenutzer-
# betrieb. Der SQLite-Fallback unten ist ausschließlich für die lokale
# Entwicklung durch eine einzelne Person gedacht — sobald eine DATABASE_URL
# gesetzt ist (Docker/Staging/Produktion), wird zwingend PostgreSQL genutzt.
DATABASE_URL = env('DATABASE_URL', default=None)
if DATABASE_URL:
    DATABASES = {'default': env.db('DATABASE_URL')}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
#
# Muss deckungsgleich mit der Frontend-Policy sein (login.ts,
# PASSWORD_MIN_LENGTH/_HAS_LETTER/_HAS_DIGIT) — das Frontend zeigt die
# Regel nur als Hilfestellung, durchgesetzt wird sie hier: wer die
# Registrierungs-API direkt aufruft (ohne Formular), muss serverseitig
# trotzdem abgelehnt werden, wenn die Regel nicht erfüllt ist.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation'
            '.UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
    {
        'NAME': 'core.validators.LetterAndDigitValidator',
    },
]

# ARCHITEKTUR.md §3.1: Argon2 zuerst, damit neue Passwort-Hashes damit
# erzeugt werden. Die übrigen Hasher bleiben als Fallback zum Verifizieren
# älterer Hashes eingetragen (Django-Standardverhalten).
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # ARCHITEKTUR.md §3.4: bei DEBUG=False keine internen Fehlerdetails/
    # Stacktraces im Response-Body, siehe core/exception_handlers.py
    'EXCEPTION_HANDLER': 'core.exception_handlers.custom_exception_handler',
}

# ARCHITEKTUR.md §3.1: Access-Token kurzlebig, nur im Antwort-Body (das
# Frontend hält ihn nur im Speicher, siehe core/auth_views.py). Refresh-Token-
# Rotation mit serverseitiger Invalidierung über den Blacklist-Store.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# CORS
# https://github.com/adamchainz/django-cors-headers
# ARCHITEKTUR.md §3.4: kein Wildcard, Origin kommt aus der Umgebung.
CORS_ALLOWED_ORIGINS = [env('FRONTEND_URL', default='http://localhost:4200')]
CORS_ALLOW_CREDENTIALS = True

# Content-Security-Policy (django-csp 4.x-Format)
# ARCHITEKTUR.md §3.4: script-src 'self' ohne unsafe-inline/unsafe-eval.
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ["'self'"],
        'script-src': ["'self'"],
        'style-src': ["'self'"],
        'img-src': ["'self'", 'data:'],
        'frame-ancestors': ["'none'"],
    },
}

# django-axes: Brute-Force-/Credential-Stuffing-Schutz (ARCHITEKTUR.md §3.1)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# Redis: Caching, siehe ARCHITEKTUR.md §1/§4. Sessions/Token-Blacklist
# laufen bewusst weiterhin über die Datenbank (Standard-Django/simplejwt-
# Mechanismus) statt über eine selbstgebaute Redis-Lösung — weniger
# Angriffsfläche/Komplexität für den MVP, siehe ARCHITEKTUR.md §2.1.
REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
    }
}

# Admin-Panel NICHT unter dem Standardpfad /admin/ (ARCHITEKTUR.md §3.4:
# Standardziel automatisierter Scanner). Pfad kommt aus der Umgebung,
# siehe config/urls.py.
ADMIN_URL_PATH = env('ADMIN_URL_PATH', default='django-admin/')

# Security-Hardening für Produktion — nur aktiv wenn DEBUG=False
# (ARCHITEKTUR.md §3.4). In lokaler Entwicklung mit DEBUG=True bewusst aus,
# da z. B. SECURE_SSL_REDIRECT den lokalen HTTP-Dev-Server sonst blockiert.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# TODO (Backend, siehe ARCHITEKTUR.md §3.6): echten Mail-Versand konfigurieren,
# sobald der Passwort-Reset-Flow den Versand tatsächlich auslöst.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
