# Generated by Django 6.1 on 2026-09-23 12:10

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_household_monthly_buffer_and_more'),
        ('finanzen', '0012_alter_category_color'),
        ('haushalt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='section',
            field=models.CharField(choices=[('obst_gemuese', 'Obst & Gemüse'), ('backwaren', 'Brot & Backwaren'), ('kuehlregal', 'Kühlregal'), ('fleisch_fisch', 'Fleisch & Fisch'), ('tiefkuehl', 'Tiefkühl'), ('vorrat', 'Vorrat'), ('getraenke', 'Getränke'), ('drogerie', 'Drogerie'), ('haushalt', 'Haushalt'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='effort',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Klein'), (2, 'Mittel'), (3, 'Groß')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='last_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rotate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rotation_members',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FolderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vertrag', 'Vertrag'), ('geraet', 'Gerät')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('notice_period_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('maintenance_interval_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_entries', to='core.household')),
                ('recurring_deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzen.recurringdeduction')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_count', models.PositiveIntegerField()),
                ('item_names', models.JSONField(default=list)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_trips', to='core.household')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finanzen.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effort', models.PositiveSmallIntegerField(choices=[(1, 'Klein'), (2, 'Mittel'), (3, 'Groß')])),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='core.household')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='haushalt.task')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('section', models.CharField(choices=[('obst_gemuese', 'Obst & Gemüse'), ('backwaren', 'Brot & Backwaren'), ('kuehlregal', 'Kühlregal'), ('fleisch_fisch', 'Fleisch & Fisch'), ('tiefkuehl', 'Tiefkühl'), ('vorrat', 'Vorrat'), ('getraenke', 'Getränke'), ('drogerie', 'Drogerie'), ('haushalt', 'Haushalt'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_memories', to='core.household')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('household'), name='unique_item_memory_per_household')],
            },
        ),
    ]
