# Generated by Django 6.1 on 2026-09-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haushalt', '0002_shoppingitem_checked_at_shoppingitem_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
