# Generated by Django 6.1 on 2026-09-25 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('TASK', 'Aufgabe'), ('CALENDAR_EVENT', 'Termin'), ('SAVINGS_GOAL', 'Sparziel'), ('HOUSEHOLD_TASK', 'Haushaltsaufgabe'), ('TRIP', 'Reise'), ('BUDGET', 'Budget')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField()),
                ('target_type', models.CharField(choices=[('TASK', 'Aufgabe'), ('CALENDAR_EVENT', 'Termin'), ('SAVINGS_GOAL', 'Sparziel'), ('HOUSEHOLD_TASK', 'Haushaltsaufgabe'), ('TRIP', 'Reise'), ('BUDGET', 'Budget')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('relation_type', models.CharField(choices=[('RELATED_TO', 'Gehört zusammen'), ('TASK_FOR', 'Aufgabe für'), ('SCHEDULED_AS', 'Eingeplant als'), ('FUNDED_BY', 'Finanziert durch'), ('AFFECTS', 'Betrifft')], default='RELATED_TO', max_length=20)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manuell'), ('SUGGESTED', 'Vorgeschlagen'), ('AUTOMATED', 'Automatisch')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='connections_source__0f70b1_idx'), models.Index(fields=['target_type', 'target_id'], name='connections_target__317538_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'target_type', 'target_id'), name='unique_connection_pair'), models.CheckConstraint(condition=models.Q(('source_type', models.F('target_type')), ('source_id', models.F('target_id')), _negated=True), name='connection_not_self'), models.CheckConstraint(condition=models.Q(('source_type__in', ['TASK', 'CALENDAR_EVENT', 'SAVINGS_GOAL', 'HOUSEHOLD_TASK', 'TRIP', 'BUDGET'])), name='connection_source_type_valid'), models.CheckConstraint(condition=models.Q(('target_type__in', ['TASK', 'CALENDAR_EVENT', 'SAVINGS_GOAL', 'HOUSEHOLD_TASK', 'TRIP', 'BUDGET'])), name='connection_target_type_valid'), models.CheckConstraint(condition=models.Q(('relation_type__in', ['RELATED_TO', 'TASK_FOR', 'SCHEDULED_AS', 'FUNDED_BY', 'AFFECTS'])), name='connection_relation_valid'), models.CheckConstraint(condition=models.Q(('origin__in', ['MANUAL', 'SUGGESTED', 'AUTOMATED'])), name='connection_origin_valid')],
            },
        ),
    ]
