# Generated by Django 6.1 on 2026-09-23 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_household_monthly_buffer_and_more'),
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('manuell', 'Manuell'), ('aufgabe', 'Haushaltsaufgabe'), ('ordner', 'Haushaltsordner')], default='manuell', max_length=10),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['household', 'source_key'], name='organisatio_househo_f8332b_idx'),
        ),
    ]
