# Generated by Django 6.1 on 2026-09-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mfabackupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdinvite',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Mitglied'), ('CHILD_ACCOUNT', 'Kind-Konto')], default='MEMBER', max_length=20),
        ),
    ]
