# Generated by Django 6.1 on 2026-09-11 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_householdinvite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='monthly_buffer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
